# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-router" do
  binary "gh-router", target: "ghr"
  binary "gh-router", target: "ghrllm.text"

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "625a03b137b44cb72359c35cfb3fe2b7efcd6f3dbaf9043e5f6990c6af30df8c"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "697ab3b3153b1eadf9959d36a8c2564be237bd21d25f3e8a3fd9984e11372364"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "89d4326985a9047377a6afdfafaf39f7e56b40c4c1dc0a90dd8fa7950a28c3bc"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cbcc852178af7814ef27e05a3c602dbc5008507f2956273cb17c95ee97e1c67f"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gh-router"
  desc "Deterministic GitHub CLI account routing"
  homepage "https://github.com/SamCullin/gh-router"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-router"

  # No zap stanza required
end
