# This file was generated by GoReleaser. DO NOT EDIT.
cask "gh-router" do
  binary "gh-router", target: "ghr"
  binary "gh-router", target: "ghrllm.text"

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "3ae2bca5225c30b2283fcd72bfbc8ae30b2aba66a2a7b2d220dde60912b72785"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "67296d71ed65cf37d619646382bdc72adc2b99446a39badc2a0591c7233387f1"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b207c11e0eeed683b309a09a53e13bcb1e17edddb11d246dc3fbff7c93129fb5"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5213223bb18fe69b9a574e9da9a9bfe32b61a0e1b64675a2d65a54abb7ac1afb"
      url "https://github.com/SamCullin/gh-router/releases/download/v#{version}/gh-router_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gh-router"
  desc "Deterministic GitHub CLI account routing"
  homepage "https://github.com/SamCullin/gh-router"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gh-router"

  # No zap stanza required
end
