# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhRouter < Formula
  desc "Deterministic GitHub CLI account routing"
  homepage "https://github.com/SamCullin/gh-router"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.2.0/gh-router_0.2.0_darwin_amd64.tar.gz"
      sha256 "438c44731b33b185137e700b2ef50b423d3810fe9ede6b2337c42b5aae8eeb0c"

      define_method(:install) do
        bin.install "gh-router"
        bin.install_symlink "gh-router" => "ghr"
        bin.install_symlink "gh-router" => "ghrllm.text"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.2.0/gh-router_0.2.0_darwin_arm64.tar.gz"
      sha256 "fdc6dfefb7b1e43583f50681209d42ddcc7ac07ccd05080ad105c998e17457d0"

      define_method(:install) do
        bin.install "gh-router"
        bin.install_symlink "gh-router" => "ghr"
        bin.install_symlink "gh-router" => "ghrllm.text"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.2.0/gh-router_0.2.0_linux_amd64.tar.gz"
      sha256 "80d53bfb9df15940df74dc42ecf24ebf63b5694f1e0934674d3431b2df314b12"
      define_method(:install) do
        bin.install "gh-router"
        bin.install_symlink "gh-router" => "ghr"
        bin.install_symlink "gh-router" => "ghrllm.text"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.2.0/gh-router_0.2.0_linux_arm64.tar.gz"
      sha256 "379bb35d1994cdd7495dfc06cff1464a12b6c6efe6ba9c45fdf6ca84377a3f0b"
      define_method(:install) do
        bin.install "gh-router"
        bin.install_symlink "gh-router" => "ghr"
        bin.install_symlink "gh-router" => "ghrllm.text"
      end
    end
  end

  test do
    system "#{bin}/gh-router", "--version"
    system "#{bin}/ghrllm.text"
  end
end
