# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhRouter < Formula
  desc "Deterministic GitHub CLI account routing"
  homepage "https://github.com/SamCullin/gh-router"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.1.0/gh-router_0.1.0_darwin_amd64.tar.gz"
      sha256 "17262992fc171e6a298d41a1b7ba69d91b362953f55bd9ea7e1c6ff93cdb0ef7"

      define_method(:install) do
        bin.install "gh-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.1.0/gh-router_0.1.0_darwin_arm64.tar.gz"
      sha256 "bd89497dd6cad0e8ec53d78c525697c9875f68c1529ab9e72c299d67cecda6f7"

      define_method(:install) do
        bin.install "gh-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.1.0/gh-router_0.1.0_linux_amd64.tar.gz"
      sha256 "c8b2cfab43f429c3f943a8b535f7c10c0600da1d261e9e62d26f148ae4438b49"
      define_method(:install) do
        bin.install "gh-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SamCullin/gh-router/releases/download/v0.1.0/gh-router_0.1.0_linux_arm64.tar.gz"
      sha256 "ecedb4290fe500d765337b756baec6a916d815406a71daad28f8e1be8ec28347"
      define_method(:install) do
        bin.install "gh-router"
      end
    end
  end

  test do
    system "#{bin}/gh-router", "--version"
  end
end
